Repository FRONTENDSCHOOL5/final-14-BangKKuseok, pull requests merged in 2023-08, with the labels that each got.

#246 ♻️ refactor: 404 페이지 배경색 지정
  src/pages/404/NotFoundPage.jsx
Labels: ♻️리팩토링

#238 ✨ feat: 채팅에서 이미지를 선택해서 올릴 수 있는 기능 추가
  src/components/common/Input/RoundedBottomInput/RoundedBottomInput.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
Labels: ✨기능 추가, ♻️리팩토링

#248 🐛 fix: 판매 상품 목록을 받아오지 못하는 문제 해결 및 버튼 추가
  src/components/PostUpload/ModalProductItem/ModalProductItemStyle.jsx
  src/components/PostUpload/ModalProductList/ModalProductList.jsx
  src/components/PostUpload/PostProductTag/PostProductTag.jsx
Labels: 🐞버그 수정, ✨기능 추가

#253 ✨ feat: 내 프로필 정보 recoil로 관리하기
  src/atoms/myProfile.js
  src/components/PostDetail/CommentItem/CommentItem.jsx
  src/components/PostDetail/CommentSection/CommentSection.jsx
  src/components/PostUpload/PostProductTag/PostProductTag.jsx
  src/components/Profile/ProfileCard/ProfileCard.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPage.jsx
  src/pages/ProfilePage/FollowPage/FollowingsPage/FollowingsPage.jsx
  src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: ✨기능 추가

#255 🐛 fix: useScroll에서 발생하는 current값을 못찾는 오류 수정
  src/hooks/useScroll.js
Labels: 🐞버그 수정

#258 ♻️ refactor: useScroll와 top버튼 사용 위치 옮기기
  src/components/common/Button/TopButton/TopButton.jsx
  src/hooks/useScroll.js
  src/layout/BasicLayout.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: 🐞버그 수정, ♻️리팩토링

#260 ♻️ refactor: 게시글 등록 시 상품 태그없이도 넘어갈 수 있도록 하기
  src/components/PostUpload/PostProductTag/PostProductTag.jsx
  src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
Labels: ♻️리팩토링

#252 🎨 style: 메인의 소셜버튼 hover시 스타일 지정하기
  src/components/common/Button/SocialButton/SocialButtonStyle.jsx
Labels: 🎨HTML/CSS

#262 ♻️ refactor: 홈, 피드 페이지 limit값을 상수로 분리
  src/api/feedApi.js
  src/api/homeApi.js
  src/constants/pagenation.js
  src/pages/FeedPage/FeedPage.jsx
  src/pages/HomePage/HomePage.jsx
Labels: ♻️리팩토링

#264 ♻️ refactor: 상품 태그 등록 기능 최적화
  src/atoms/feed.js
  src/atoms/post.js
  src/components/PostUpload/ModalProductItem/ModalProductItem.jsx
  src/components/PostUpload/ModalProductList/ModalProductList.jsx
  src/components/PostUpload/PostProductTag/PostProductTag.jsx
  src/components/PostUpload/PostProductTag/PostProductTagStyle.jsx
  src/components/PostUpload/PostTextWrite/PostTextWrite.jsx
  src/components/PostUpload/ProductBubble/ProductBubble.jsx
  src/components/PostUpload/ProductTag/ProductTag.jsx
  src/hooks/useBubbleLocation.js
  src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
Labels: ♻️리팩토링

#268 🐛 fix: reference.current를 찾지못하는 오류 해결
  src/hooks/useScroll.js
Labels: 🐞버그 수정

#249 🎨 style: Navbar 디자인 수정
  src/assets/icons/icon-upload.svg
  src/components/common/Navbar/Navbar.jsx
  src/components/common/Navbar/NavbarStyle.jsx
Labels: 🎨HTML/CSS

#270 ♻️ refactor: safari에서 봤을 때 100vh 스크롤 해결
  src/App.js
  src/components/LoginSignUp/LoginSignUp/LoginSignUpStyle.jsx
  src/components/LoginSignUp/Main/MainStyle.jsx
  src/components/LoginSignUp/SetUserProfile/SetUserProfileStyle.jsx
  src/components/LoginSignUp/Welcome/WelcomeStyle.jsx
  src/components/common/BottomSheet/BottomSheetStyle.jsx
  src/components/common/Confirm/ConfirmStyle.jsx
  src/components/common/Spinner/Spinner.jsx
  src/layout/BasicLayout.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPageStyle.jsx
  src/pages/FeedPage/FeedPageStyle.jsx
  src/pages/SplashPage/SplashStyle.jsx
  src/styles/GlobalStyle.js
Labels: ♻️리팩토링, 🎨HTML/CSS

#272 ♻️ refactor: meta 태그를 사용한 SEO
  public/index.html
Labels: ♻️리팩토링

#274 🐛 _redirects 파일 추가하여 netlify 404 에러 수정
  public/_redirects
Labels: 🐞버그 수정, 🌎배포

#241 ♻️ refactor: 헤더 코드 간소화 및 리팩토링
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/pages/ChatPage/ChatListPage/ChatListPage.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/ProductPage/ProductEditPage/ProductEditPage.jsx
  src/pages/ProductPage/ProductUploadPage/ProductUploadPage.jsx
  src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPage.jsx
  src/pages/ProfilePage/FollowPage/FollowingsPage/FollowingsPage.jsx
  src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: ♻️리팩토링

#276 ♻️ refactor: react-query 로직 최적화
  src/api/followApi.js
  src/constants/pagenation.js
  src/hooks/useInfiniteDataQuery.js
  src/hooks/useReportMutation.js
  src/pages/FeedPage/FeedPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPage.jsx
  src/pages/ProfilePage/FollowPage/FollowingsPage/FollowingsPage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: ♻️리팩토링

#279 ♻️ refactor: useModal Custom hook 생성 및 리코일로 관리하여 BottomSheet 리팩토링
  src/atoms/modal.js
  src/components/PostDetail/CommentItem/CommentItem.jsx
  src/components/PostDetail/CommentSection/CommentSection.jsx
  src/components/PostUpload/ModalProductItem/ModalProductItem.jsx
  src/components/PostUpload/ModalProductList/ModalProductList.jsx
  src/components/PostUpload/PostProductTag/PostProductTag.jsx
  src/components/PostUpload/PostTextWrite/PostTextWrite.jsx
  src/components/common/BottomSheet/BottomSheet.jsx
  src/components/common/BottomSheet/ListModal.jsx
  src/hooks/useModal.js
  src/pages/ChatPage/ChatListPage/ChatListPage.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: ♻️리팩토링

#281 🐛 fix: 게시글 삭제시 오류 해결하기 위해 navigate('/') 추가
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 🐞버그 수정

#282 ♻️ refactor: Header 리팩토링 및 버튼에 aria-label 추가
  src/components/PostDetail/CommentItem/CommentItem.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx
  src/pages/ChatPage/ChatListPage/ChatListPage.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
Labels: 🐞버그 수정, ♻️리팩토링

#284 ✨ feat: 게시글에 태그된 상품 목록 저장하기
  src/atoms/post.js
  src/components/PostUpload/PostImgUpload/PostImgUploadStyle.jsx
  src/components/PostUpload/PostProductTag/PostProductTag.jsx
  src/components/PostUpload/PostProductTag/PostProductTagStyle.jsx
  src/components/PostUpload/PostTextWrite/PostTextWrite.jsx
  src/components/PostUpload/PostTextWrite/PostTextWriteStyle.jsx
  src/components/PostUpload/ProductBubble/ProductBubble.jsx
  src/components/PostUpload/ProductBubble/ProductBubbleStyle.jsx
  src/components/PostUpload/ProductTag/ProductTag.jsx
  src/components/PostUpload/ProductTagItem/ProductTagItem.jsx
  src/components/common/BottomSheet/BottomSheetStyle.jsx
  src/components/common/Card/PostCard/PostCard.jsx
  src/components/common/Card/PostCard/PostCardStyle.jsx
  src/constants/common.js
  src/hooks/useBubbleLocation.js
  src/hooks/useScroll.js
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPageStyle.jsx
  src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
Labels: ✨기능 추가, ♻️리팩토링

#285 ♻️ refactor: useConfirm 커스텀훅 생성 및 Confirm 리팩토링
  src/atoms/confirm.js
  src/components/common/Confirm/Confirm.jsx
  src/hooks/useConfirm.js
  src/pages/ChatPage/ChatListPage/ChatListPage.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: ♻️리팩토링
