Repository FRONTENDSCHOOL5/final-14-BangKKuseok, pull requests merged in 2023-06, with the labels that each got.

#5 🐛 fix: 글꼴 관련 이슈 해결을 위해 폰트 경로 및 파일 수정
  src/assets/fonts/Pretendard/Pretendard-Medium.otf
  src/assets/fonts/Pretendard/Pretendard-Medium.woff
  src/assets/fonts/Pretendard/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard/Pretendard-Regular.otf
  src/assets/fonts/Pretendard/Pretendard-Regular.woff
  src/assets/fonts/Pretendard/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard/Pretendard-SemiBold.otf
  src/assets/fonts/Pretendard/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard/Pretendard-SemiBold.woff2
  src/styles/GlobalStyle.js
  src/styles/fonts.css
Labels: 🐞버그 수정

#8 🎨 style: 버튼 공통 UI 컴포넌트 구현
  src/components/common/Button/Button.jsx
  src/components/common/Button/SocialButton.jsx
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: 🎨HTML/CSS

#13 🎨 style: 공통 카드 UI 컴포넌트 구현 #6
  src/assets/icons/icon-message-fill.svg
  src/assets/icons/icon-message-small.svg
  src/assets/icons/icon-message.svg
  src/assets/icons/icon-upload.svg
  src/assets/images/image-edit.png
  src/assets/images/image-upload.png
  src/assets/images/prof-upload.png
  src/components/common/Card/Heart.jsx
  src/components/common/Card/PostCard.jsx
  src/components/common/Card/ProductCard.jsx
  src/components/common/ComponentsLibrary.jsx
Labels: 🎨HTML/CSS

#15 🎨 style: 페이지별 Header UI 컴포넌트 구현 (#11)
  src/assets/icons/icon-arrow-left.svg
  src/assets/icons/icon-more.svg
  src/assets/icons/icon-search.svg
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
Labels: 🎨HTML/CSS

#16 🎨 style: 공통 Input UI 구현
  src/components/common/Input/Input.jsx
Labels: 🎨HTML/CSS

#17 🎨 style: Tabs 공통 UI 구현
  src/components/common/ComponentsLibrary.jsx
  src/components/common/Tab/SpaceTabs.jsx
  src/components/common/Tab/ViewTabs.jsx
  src/components/common/Tabs/SpaceTabs.jsx
  src/components/common/Tabs/ViewTabs.jsx
Labels: 🎨HTML/CSS

#20 🎨 style: RoundedInput 공통 UI 컴포넌트 구현
  src/assets/icons/icon-arrow-top.svg
  src/components/common/Header/Header.jsx
  src/components/common/Input/RoundedBottomInput copy.jsx
  src/components/common/Input/RoundedBottomInput.jsx
  src/components/common/Input/RoundedBottomInput/RoundedBottomInput.jsx
  src/components/common/Input/RoundedBottomInput/RoundedBottomInputStyle.jsx
  src/components/common/Input/RoundedInput.jsx
  src/components/common/Input/RoundedInput/RoundedInput.jsx
  src/components/common/Input/RoundedInput/RoundedInputStyle.jsx
  src/styles/GlobalStyle.js
Labels: 🎨HTML/CSS

#23 🎨 style: Navbar 공통 UI 컴포넌트 구현
  src/components/common/Navbar/Navbar.jsx
  src/components/common/Navbar/NavbarStyle.jsx
Labels: 🎨HTML/CSS

#22 🎨 style: 갤러리 공통 UI 컴포넌트 구현
  src/components/common/Gallery/Gallery.jsx
Labels: 🎨HTML/CSS

#24 🎨 style: ProfileImageUpload UI 컴포넌트 구현
  src/assets/images/profile-large.png
  src/assets/images/profile.png
  src/components/common/ImageUpload/ImageUpload.jsx
  src/components/common/ProfileImageUpload/ProfileImageUpload.jsx
  src/components/common/ProfileImageUpload/ProfileImageUploadStyle.jsx
Labels: 🎨HTML/CSS

#28 🎨 style: Confirm창 UI 컴포넌트 구현
  src/components/common/Alert/Alert.jsx
  src/components/common/Confirm/Confirm.jsx
  src/components/common/Confirm/ConfirmStyle.jsx
Labels: 🎨HTML/CSS

#32 ♻️ refactor: Button 컴포넌트 폴더 구조 변경 및 컨벤션에따라 Carousel 코드 수정
  src/components/common/Button/Button/Button.jsx
  src/components/common/Button/Button/ButtonStyle.jsx
  src/components/common/Button/SocialButton/SocialButton.jsx
  src/components/common/Button/SocialButton/SocialButtonStyle.jsx
  src/components/common/Carousel/Carousel.jsx
Labels: ♻️리팩토링

#36 🎨 style: Navbar 공통 UI 컴포넌트 수정
  src/components/common/Navbar/NavbarStyle.jsx
Labels: 🐞버그 수정, 🎨HTML/CSS

#34 ♻️ refactor: 카드 UI 컴포넌트 리팩토링
  src/components/common/Card/Heart.jsx
  src/components/common/Card/Heart/Heart.jsx
  src/components/common/Card/Heart/HeartStyle.jsx
  src/components/common/Card/PostCard.jsx
  src/components/common/Card/PostCard/PostCard.jsx
  src/components/common/Card/PostCard/PostCardStyle.jsx
  src/components/common/Card/ProductCard.jsx
  src/components/common/Card/ProductCard/ProductCard.jsx
  src/components/common/Card/ProductCard/ProductCardStyle.jsx
  src/utils/getTime.js
  src/utils/test.js
Labels: ✨기능 추가, ♻️리팩토링, 🎨HTML/CSS

#41 ♻️ refactor: Header UI 컴포넌트 리팩토링
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
Labels: ♻️리팩토링, 🎨HTML/CSS

#44 🎨 style: Navbar 컴포넌트 반응형 너비 적용
  src/components/common/Navbar/NavbarStyle.jsx
Labels: 🎨HTML/CSS

#45 ♻️ refactor: Gallery 컴포넌트 데이터 구조 리팩토링 및 반응형 디자인 적용
  src/components/common/Gallery/Gallery.jsx
Labels: ♻️리팩토링, 🎨HTML/CSS

#46 ♻️ refactor: ViewTabs 마크업 구조 변경 및 props 수정
  src/components/common/Tabs/ViewTabs.jsx
Labels: ♻️리팩토링, 🎨HTML/CSS

#47 ✨feat: 공통으로 사용되는 BasicLayout 컴포넌트 구현 및 mock 데이터 추가
  src/layout/BasicLayout.jsx
  src/mock/mockData.js
Labels: ✨기능 추가, 🎨HTML/CSS

#48 🎨 style: 프로필 페이지 마크업
  src/assets/fonts/Pretendard/Pretendard-Bold.otf
  src/assets/fonts/Pretendard/Pretendard-Bold.woff
  src/assets/fonts/Pretendard/Pretendard-Bold.woff2
  src/assets/images/profile-large.png
  src/assets/images/profile.png
  src/components/Profile/PostList/PostList.jsx
  src/components/Profile/PostList/PostListStyle.jsx
  src/components/Profile/ProductList/ProductList.jsx
  src/components/Profile/ProductList/ProductListStyle.jsx
  src/components/Profile/ProfileCard/ProfileCard.jsx
  src/components/Profile/ProfileCard/ProfileCardStyle.jsx
  src/pages/ProfilePage/MyProfilePage/MyProfilePage.jsx
  src/styles/fonts.css
  src/utils/filterPosts.js
Labels: 🎨HTML/CSS

#51 🎨 style: 공통 Modal UI 컴포넌트 구현
  src/components/common/BottomSheet/BasicModal.jsx
  src/components/common/BottomSheet/BottomSheet.jsx
  src/components/common/BottomSheet/BottomSheetStyle.jsx
  src/components/common/BottomSheet/ListModal.jsx
  src/components/common/Modal/Modal.jsx
Labels: 🎨HTML/CSS

#57 ✨ feat: recoil 사용을 위한 atoms 폴더 및 파일 추가 및 공통 변수 추가
  src/App.js
  src/atoms/post.js
  src/constants/spaces.js
  src/layout/BasicLayout.jsx
  src/styles/theme.js
Labels: ✨기능 추가

#60 ♻️ refactor: BottomSheet 컴포넌트 코드 최소화 리팩토링
  src/components/common/BottomSheet/BasicModal.jsx
  src/components/common/BottomSheet/BottomSheet.jsx
  src/components/common/BottomSheet/BottomSheetStyle.jsx
  src/components/common/BottomSheet/ListModal.jsx
  src/layout/BasicLayout.jsx
Labels: ♻️리팩토링

#61 ✨ feat: 홈페이지 마크업 및 기능 구현
  src/components/common/Carousel/CarouselStyle.jsx
  src/components/common/Tabs/SpaceTabs.jsx
  src/pages/HomePage/HomePage.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#59 ✨ feat: 게시글 업로드 페이지 마크업 및 기능 구현
  src/assets/icons/icon-add-tag.svg
  src/assets/icons/icon-delete.svg
  src/assets/images/image-upload.png
  src/components/PostUpload/ModalProductItem/ModalProductItem.jsx
  src/components/PostUpload/ModalProductItem/ModalProductItemStyle.jsx
  src/components/PostUpload/ModalProductList/ModalProductList.jsx
  src/components/PostUpload/ModalProductList/ModalProductListStyle.jsx
  src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
  src/components/PostUpload/PostImgUpload/PostImgUploadStyle.jsx
  src/components/PostUpload/PostProductTag/PostProductTag.jsx
  src/components/PostUpload/PostProductTag/PostProductTagStyle.jsx
  src/components/PostUpload/PostTextWrite/PostTextWrite.jsx
  src/components/PostUpload/PostTextWrite/PostTextWriteStyle.jsx
  src/components/PostUpload/ProductBubble/ProductBubble.jsx
  src/components/PostUpload/ProductBubble/ProductBubbleStyle.jsx
  src/components/PostUpload/ProductTag/ProductTag.jsx
  src/components/common/BottomSheet/BottomSheetStyle.jsx
  src/components/common/Header/Header.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
  src/pages/Router.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#65 🎨 style: 메인, 로그인, 회원가입, 프로필 설정 마크업 및 기능 구현 (#52)
  src/components/LoginSignUp/Login/Login.jsx
  src/components/LoginSignUp/Login/LoginStyle.jsx
  src/components/LoginSignUp/Main/Main.jsx
  src/components/LoginSignUp/Main/MainStyle.jsx
  src/components/LoginSignUp/SetUserProfile/SetUserProfile.jsx
  src/components/LoginSignUp/SetUserProfile/SetUserProfileStyle.jsx
  src/components/LoginSignUp/SignUp/SignUp.jsx
  src/components/LoginSignUp/SignUp/SignUpStyle.jsx
  src/components/common/Button/SocialButton/SocialButtonStyle.jsx
  src/components/common/Input/Input.jsx
  src/components/common/Input/InputStyle.jsx
  src/components/common/ProfileImageUpload/ProfileImageUpload.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/Router.jsx
  src/pages/SignupPage/SignupPage.jsx
Labels: 🎨HTML/CSS

#70 ✨ feat: 프로필 페이지 기본 기능 구현 및 관련 마크업 수정
  src/assets/icons/icon-message-fill-subCoral.svg
  src/assets/icons/icon-share.svg
  src/components/Profile/PostList/PostList.jsx
  src/components/Profile/PostList/PostListStyle.jsx
  src/components/Profile/ProductDetailCard/ProductDetailCard.jsx
  src/components/Profile/ProductDetailCard/ProductDetailCardStyle.jsx
  src/components/Profile/ProductList/ProductList.jsx
  src/components/Profile/ProductList/ProductListStyle.jsx
  src/components/Profile/ProfileCard/ProfileCard.jsx
  src/components/Profile/ProfileCard/ProfileCardStyle.jsx
  src/components/common/BottomSheet/BottomSheetStyle.jsx
  src/components/common/Button/Button/ButtonStyle.jsx
  src/components/common/Card/PostCard/PostCard.jsx
  src/components/common/Card/PostCard/PostCardStyle.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Tabs/ViewTabs.jsx
  src/components/common/UserSimpleInfo/UserSimpleInfo.jsx
  src/components/common/UserSimpleInfo/UserSimpleStyle.jsx
  src/pages/ProfilePage/MyProfilePage/MyProfilePage.jsx
  src/pages/Router.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#69 🐛 fix: 홈페이지 Styled component 위치 수정
  src/pages/HomePage/HomePage.jsx
Labels: 🐞버그 수정

#73 🐛 fix: a 태그를 Link 컴포넌트로 대체하여 href 오류 해결 (#72)
  src/components/LoginSignUp/Login/Login.jsx
  src/components/LoginSignUp/Main/Main.jsx
  src/components/LoginSignUp/SignUp/SignUp.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/SignupPage/SignupPage.jsx
Labels: 🐞버그 수정

#75 ♻️ refactor: confirm 리팩토링
  src/components/common/Confirm/Confirm.jsx
  src/components/common/Confirm/ConfirmStyle.jsx
Labels: ♻️리팩토링

#79 ♻️ refactor: SetUserProfile 컴포넌트 폼 입력 부분 분리
  src/components/LoginSignUp/SetUserProfile/SetUserProfile.jsx
  src/components/LoginSignUp/SetUserProfile/SetUserProfileForm.jsx
  src/components/LoginSignUp/SetUserProfile/SetUserProfileFormStyle.jsx
  src/components/LoginSignUp/SetUserProfile/SetUserProfileStyle.jsx
  src/components/common/ProfileImageUpload/ProfileImageUpload.jsx
  src/components/common/ProfileImageUpload/ProfileImageUploadStyle.jsx
Labels: ♻️리팩토링

#80 ✨ feat: 검색창 마크업 및 기능 구현
  src/components/Profile/PostList/PostList.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Input/RoundedInput/RoundedInput.jsx
  src/components/common/Input/RoundedInput/RoundedInputStyle.jsx
  src/components/common/UserSimpleInfo/Skeleton/Skeleton.jsx
  src/components/common/UserSimpleInfo/Skeleton/SkeletonStyle.jsx
  src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx
  src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleStyle.jsx
  src/mock/mockData.js
  src/pages/HomePage/HomePage.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#81 ✨ feat: 게시글 등록 페이지 API 연동하여 게시글 등록 구현
  src/api/axiosInstance.js
  src/api/imgApi.js
  src/api/postApi.js
  src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
  src/components/PostUpload/PostProductTag/PostProductTag.jsx
  src/components/PostUpload/PostTextWrite/PostTextWrite.jsx
  src/components/common/Navbar/Navbar.jsx
  src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
Labels: ✨기능 추가

#84 ✨ feat: 프로필 수정 페이지 마크업 및 API 연동하여 수정 기능 구현
  src/api/profileApi.js
  src/components/LoginSignUp/SetUserProfile/SetUserProfileForm.jsx
  src/components/Profile/ProfileCard/ProfileCard.jsx
  src/components/common/Header/Header.jsx
  src/components/common/ProfileImageUpload/ProfileImageUpload.jsx
  src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/UserProfilePage/UserProfilePage.jsx
  src/pages/Router.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#85 ✨ feat: 게시글 상세페이지 API 연동 및 게시글 수정페이지 마크업과 구현
  src/api/postApi.js
  src/components/PostEdit/PostImgEdit/PostImgEdit.jsx
  src/components/PostEdit/PostImgEdit/PostImgEditStyle.jsx
  src/components/PostEdit/PostTextEdit/PostTextEdit.jsx
  src/components/PostEdit/PostTextEdit/PostTextEditStyle.jsx
  src/components/PostUpload/PostImgUpload/PostImgUploadStyle.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPageStyle.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#87 ✨ feat: 게시글 상세페이지에서의 삭제 및 신고 기능 구현
  src/api/postApi.js
  src/assets/icons/icon-spinner.svg
  src/atoms/post.js
  src/components/common/Spinner/Spinner.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
Labels: ✨기능 추가

#93 🐛 fix: 게시글 업로드 시 이미지 변경 취소 오류와 상품목록 조건의 오류 발생
  src/components/PostUpload/ModalProductList/ModalProductList.jsx
  src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
Labels: 🐞버그 수정

#94 🐛 fix: 프로필 수정 시 이미지 변경 후, 다시 업로드 버튼을 누르고 취소할 경우 발생하는 오류 해결
  src/components/common/ProfileImageUpload/ProfileImageUpload.jsx
Labels: 🐞버그 수정

#95 ✨ feat: api 연동하여 댓글 작성,삭제,신고 기능 구현
  src/api/commentApi.js
  src/api/postApi.js
  src/components/PostDetail/CommentItem/CommentItem.jsx
  src/components/PostDetail/CommentItem/CommentItemStyle.jsx
  src/components/PostDetail/CommentSection/CommentSection.jsx
  src/components/common/Input/RoundedBottomInput/RoundedBottomInput.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPageStyle.jsx
Labels: ✨기능 추가

#98 ⚙️ chore: react query devtools 적용 (#97)
  src/App.js
Labels: ⚙️설정

#99 ✨ feat: ProfilePage 사용자에 따른 모달창 구분 및 Confirm 연결
  src/api/postApi.js
  src/api/productApi.js
  src/api/profileApi.js
  src/components/Profile/PostList/PostList.jsx
  src/components/Profile/ProductDetailCard/ProductDetailCard.jsx
  src/components/Profile/ProfileCard/ProfileCard.jsx
  src/components/common/Card/PostCard/PostCard.jsx
  src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleStyle.jsx
  src/pages/ProductPage/ProductEditPage/ProductEditPage.jsx
  src/pages/ProductPage/ProductPage.jsx
  src/pages/ProductPage/ProductUploadPage/ProductUploadPage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
  src/pages/Router.jsx
  src/utils/filterPosts.js
Labels: ✨기능 추가

#101 ♻️ refactor: PostList 컴포넌트 재사용성을 위해 props 값 수정
  src/components/Profile/PostList/PostList.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: ♻️리팩토링

#104 🎨 style: 피드 페이지 마크업 및 데이터 불러오기
  src/api/feedApi.js
  src/atoms/feed.js
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/FeedPageStyle.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#106 🐛 fix: 게시글 상세 페이지의 myprofile을 찾지 못하는 문제 해결
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 🐞버그 수정

#108 🎨 style: 404페이지 마크업
  src/pages/404/NotFoundPage.jsx
Labels: 🎨HTML/CSS

#109 🎨 style: splash 페이지 구현 및 마크업
  src/assets/images/furnitures.png
  src/pages/SplashPage/SplashPage.jsx
  src/pages/SplashPage/SplashPageStyle.jsx
Labels: 🎨HTML/CSS

#111 ✨ feat: api 연동하여 로그인, 회원가입 기능 구현 (#66)
  src/api/loginApi.js
  src/api/signupApi.js
  src/components/LoginSignUp/Login/Login.jsx
  src/components/LoginSignUp/SignUp/SignUp.jsx
  src/components/common/Input/Input.jsx
  src/components/common/Input/InputStyle.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/SignupPage/SignupPage.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#115 🚚 rename: splash 이미지 파일 추가
  src/assets/images/logo-large.png
  src/pages/SplashPage/SplashPage.jsx
Labels: 🐞버그 수정

#116 🐛 fix: 페이지 전환 후 돌아올 경우 피드 데이터 리패치하지않는 문제 해결
  src/api/feedApi.js
  src/components/common/Card/PostCard/PostCard.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/pages/FeedPage/FeedPage.jsx
Labels: 🐞버그 수정

#118 ✨ feat: 홈페이지 게시글 API 연동
  src/api/homeApi.js
  src/components/common/Gallery/Gallery.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/utils/filterPosts.js
Labels: ✨기능 추가

#120 🐛 fix: 댓글 기능 적용시 데이터가 바로 적용되지 않는 문제 해결
  src/api/postApi.js
  src/components/PostDetail/CommentSection/CommentSection.jsx
  src/components/Profile/PostList/PostList.jsx
  src/components/common/Card/PostCard/PostCard.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 🐞버그 수정, ♻️리팩토링

#122 ✨ feat: 상품 등록, 수정 마크업 및 기능 구현
  src/api/productApi.js
  src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
  src/components/PostUpload/PostImgUpload/PostImgUploadStyle.jsx
  src/components/Product/ProductForm/ProductForm.jsx
  src/components/Product/ProductForm/ProductFormStyle.jsx
  src/components/Profile/ProductDetailCard/ProductDetailCard.jsx
  src/components/Profile/ProductList/ProductList.jsx
  src/components/common/Input/Input.jsx
  src/constants/validate.js
  src/hooks/test.js
  src/hooks/useInputs.js
  src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
  src/pages/ProductPage/ProductEditPage/ProductEditPage.jsx
  src/pages/ProductPage/ProductUploadPage/ProductUploadPage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#125 🐛 fix: 프로필 수정 시 프로필 페이지에서 이전 데이터를 요청하는 오류 해결
  src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx
Labels: 🐞버그 수정

#123 ✨ feat: 검색 API 연동 및 추가 기능 구현
  src/api/searchApi.js
  src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx
  src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleStyle.jsx
  src/hooks/useDebounce.js
  src/pages/SearchPage/SearchPage.jsx
Labels: ✨기능 추가, ♻️리팩토링, 🎨HTML/CSS

#124 ✨ feat: api 연동하여 프로필 설정 기능 구현
  src/api/signupApi.js
  src/components/LoginSignUp/Login/Login.jsx
  src/components/LoginSignUp/Login/LoginStyle.jsx
  src/components/LoginSignUp/SetUserProfile/SetUserProfile.jsx
  src/components/LoginSignUp/SetUserProfile/SetUserProfileForm.jsx
  src/components/common/Input/InputStyle.jsx
  src/pages/SignupPage/SignupPage.jsx
Labels: ✨기능 추가

#131 ✨ feat: 검색 결과 7개씩 보여주는 기능 추가
  src/pages/SearchPage/SearchPage.jsx
Labels: ✨기능 추가

#133 🐛 fix: 검색 결과 목록이 7개 이하일 때 더보기 버튼 안보이게 수정
  src/pages/SearchPage/SearchPage.jsx
Labels: 🐞버그 수정

#134 🎨 style: 회원가입 후 로그인으로 넘어가는 웰컴 페이지 제작
  package-lock.json
  package.json
  src/assets/images/drawer-img.png
  src/assets/lottie/confetti.json
  src/components/LoginSignUp/Welcome/Welcome.jsx
  src/components/LoginSignUp/Welcome/WelcomeStyle.jsx
  src/pages/SignupPage/SignupPage.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#135 🎨 style: 채팅 페이지 마크업 구현
  src/assets/images/img-btn.png
  src/components/common/Confirm/Confirm.jsx
  src/components/common/Input/RoundedBottomInput/RoundedBottomInput.jsx
  src/components/common/Input/RoundedBottomInput/RoundedBottomInputStyle.jsx
  src/components/common/UserSimpleInfo/OtherSimpleInfo/OtherSimpleInfo.jsx
  src/mock/mockData.js
  src/pages/ChatPage/ChatListPage/ChatListPage.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPageStyle.jsx
Labels: ✨기능 추가, 🎨HTML/CSS

#138 🎨 style: 스플래시 페이지 애니메이션 수정
  src/pages/SplashPage/SplashPage.jsx
  src/pages/SplashPage/SplashPageStyle.jsx
Labels: 🎨HTML/CSS

#141 🐛 fix: 로그아웃 후 재 로그인 시 기존 데이터가 보이는 오류 해결
  src/api/axiosInstance.js
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: 🐞버그 수정

#143 🎨 style: 메인페이지 레이아웃 및 디자인 수정
  src/assets/images/spotlight.png
  src/components/LoginSignUp/Main/Furniture/Furniture.jsx
  src/components/LoginSignUp/Main/Furniture/Sofa.jsx
  src/components/LoginSignUp/Main/Main.jsx
  src/components/LoginSignUp/Main/MainStyle.jsx
Labels: 🎨HTML/CSS

#144 ♻️ refactor: 다른 서비스 사용자 경우 게시글 및 상품 예외 처리
  src/components/Profile/PostList/PostList.jsx
  src/components/Profile/ProductDetailCard/ProductDetailCard.jsx
  src/components/Profile/ProductList/ProductListStyle.jsx
  src/components/common/Card/PostCard/PostCard.jsx
  src/components/common/Card/PostCard/PostCardStyle.jsx
  src/components/common/Card/ProductCard/ProductCard.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 🐞버그 수정, ♻️리팩토링

#147 🐛 fix: feed 페이지에서 데이터없을때 search로 이동가능하도록 하기
  src/pages/FeedPage/FeedPage.jsx
Labels: 🐞버그 수정

#148 ✨ feat: 프로필 수정에서 이미 가입된 ID를 입력할 경우 경고메시지를 출력하는 기능 구현
  src/api/profileApi.js
  src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx
Labels: ✨기능 추가

#153 ✨ feat: FeedApi와 캐러셀 연동 및 좋아요순 정렬
  src/components/common/Carousel/Carousel.jsx
  src/components/common/Carousel/CarouselStyle.jsx
  src/components/common/Tabs/SpaceTabs.jsx
  src/pages/HomePage/HomePage.jsx
Labels: ✨기능 추가, ♻️리팩토링

#151 🐛 fix: 게시글 이미지 오류 처리
  src/components/common/Card/PostCard/PostCard.jsx
Labels: 🐞버그 수정

#154 ♻️ refactor: 게시글 작성 시 불러오는 상품목록 api 연동하기
  src/atoms/post.js
  src/components/PostUpload/ModalProductList/ModalProductList.jsx
  src/components/PostUpload/ModalProductList/ModalProductListStyle.jsx
  src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
Labels: ♻️리팩토링

#150 ✨ feat: 팔로워, 언팔로우 기능 추가
  src/api/followApi.js
  src/components/Profile/ProfileCard/ProfileCard.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/components/common/Navbar/NavbarStyle.jsx
  src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx
  src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleStyle.jsx
  src/hooks/useObserver.js
  src/pages/FeedPage/FeedPage.jsx
  src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPage.jsx
  src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPageStyle.jsx
  src/pages/ProfilePage/FollowPage/FollowingsPage/FollowingsPage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: ✨기능 추가

#162 🎨 style: 채팅 미리보기 텍스트 최근 채팅으로 수정
  src/mock/mockData.js
  src/pages/ChatPage/ChatListPage/ChatListPage.jsx
Labels: ♻️리팩토링, 🎨HTML/CSS

#159 ✨ feat: user클릭시 해당 profile로 이동하기
  src/components/PostDetail/CommentItem/CommentItem.jsx
  src/components/Profile/PostList/PostList.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: ✨기능 추가

#156 🎨 style: 파비콘 등록
  public/favicon.ico
  public/index.html
Labels: 🎨HTML/CSS

#165 ♻️ refactor: 유저 프로필 페이지에서 이미지 없을 때 대체텍스트 대신 기본 프로필 이미지로 수정
  src/components/Profile/ProfileCard/ProfileCard.jsx
Labels: 🐞버그 수정, ♻️리팩토링

#167 🎨 style: 메인페이지 레이아웃 수정
  src/components/LoginSignUp/Main/MainStyle.jsx
Labels: ♻️리팩토링, 🎨HTML/CSS

#168 ✨ feat: url에서 주소를 직접 입력했을 경우와 로그인 상태가 아닐 때 접근 방지
  src/components/LoginSignUp/Login/Login.jsx
  src/components/LoginSignUp/SignUp/SignUp.jsx
  src/components/common/Navbar/Navbar.jsx
  src/components/common/Navbar/NavbarStyle.jsx
  src/pages/AuthenticatedPage/PrivateRoutePage.jsx
  src/pages/AuthenticatedPage/PublicRoutePage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
  src/pages/Router.jsx
Labels: ✨기능 추가, ♻️리팩토링

#170 🐛 fix: User 프로필 페이지에서 채팅 버튼 눌렀을 때 chatRoom페이지로 이동하지 않는 오류 수정
  src/components/Profile/ProfileCard/ProfileCard.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPageStyle.jsx
  src/pages/Router.jsx
Labels: 🐞버그 수정

#173 🐛 fix: 회원가입 후 빈화면이 뜨는 오류 해결
  src/pages/SignupPage/SignupPage.jsx
Labels: 🐞버그 수정

#180 🚚 rename: OtherSimpleInfo의 styled-component 변수명 수정
  src/components/common/UserSimpleInfo/OtherSimpleInfo/OtherSimpleInfo.jsx
Labels: ♻️리팩토링, 🎨HTML/CSS

#178 🐛 fix: 피드, 팔로워, 팔로잉 페이지 무한 스크롤 기능 오류 해결
  src/pages/FeedPage/FeedPage.jsx
  src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPage.jsx
  src/pages/ProfilePage/FollowPage/FollowingsPage/FollowingsPage.jsx
Labels: 🐞버그 수정

#185 🎨 style: HomePage 탭 버튼 눌렀을 때 크기 달라지는 디자인 수정
  src/components/common/Tabs/SpaceTabs.jsx
Labels: 🎨HTML/CSS

#190 🐛 fix: 회원가입 성공 후 기본 이미지 세팅 오류 해결
  src/pages/SignupPage/SignupPage.jsx
Labels: ♻️리팩토링

#187 🎨 style: 캐러셀 목데이터 디자인 수정
  src/mock/mockData.js
Labels: 🎨HTML/CSS

#191 🐛 fix: fadeout 기능 재적용
  src/pages/SplashPage/Splash.jsx
  src/pages/SplashPage/SplashStyle.jsx
Labels: ♻️리팩토링

#192 🐛 fix: 팔로우한 계정 없을 때 캐러셀 링크 클릭하면 발생하는 오류 수정
  src/components/common/Carousel/Carousel.jsx
  src/mock/mockData.js
Labels: 🐞버그 수정

#194 🐛 fix: 프로필 설정에서 이미 가입된 아이디를 대문자로 입력하고 바로 방꾸석 시작하기 버튼을 눌렀을때 가입되는 오류 해결
  src/pages/SignupPage/SignupPage.jsx
Labels: 🐞버그 수정

#200 🐛 fix: 게시글 수정 페이지 axios함수 변경에 따른 props값 수정 (#199)
  src/api/postApi.js
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
Labels: 🐞버그 수정

#198 ✨ feat: toast message 기능 추가
  package-lock.json
  package.json
  src/components/PostUpload/PostTextWrite/PostTextWrite.jsx
  src/components/common/Tabs/SpaceTabs.jsx
  src/components/common/Toast/Toast.jsx
  src/constants/common.js
  src/layout/BasicLayout.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: ✨기능 추가

#202 🐛 fix: HomePage 게시글이 없을 때 '아직 등록된 게시물이 없습니다' 메시지 출력 안되는 오류 수정
  src/assets/icons/icon-search.svg
  src/components/common/Header/HeaderStyle.jsx
  src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx
  src/pages/HomePage/HomePage.jsx
Labels: 🐞버그 수정, ♻️리팩토링

#196 🎨 style: 검색 아이콘 shadow 수정
  src/assets/icons/icon-search.svg
Labels: 🎨HTML/CSS

#204 🎨 style: 애플리케이션 배경색 및 box-shadow 설정
  src/components/LoginSignUp/Main/MainStyle.jsx
  src/components/LoginSignUp/SignUp/SignUpStyle.jsx
  src/layout/BasicLayout.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/SignupPage/SignupPage.jsx
  src/pages/SplashPage/SplashStyle.jsx
  src/styles/GlobalStyle.js
Labels: 🎨HTML/CSS

#206 📝 docs: README.md 수정 (#158)
  README.md
Labels: 📜문서
