Repository FRONTENDSCHOOL5/final-14-BangKKuseok, pull requests merged in 2023-07, with the labels that each got.

#207 📜 docs: README.md 수정 (2023.06.30)
  README.md
Labels: 📜문서

#209 ♻️ refactor: 게시글 등록 시 드래그해도 상품 태그 가능하도록 수정
  src/components/PostUpload/PostProductTag/PostProductTag.jsx
  src/components/PostUpload/PostProductTag/PostProductTagStyle.jsx
  src/components/PostUpload/ProductBubble/ProductBubble.jsx
  src/constants/common.js
  src/hooks/useBubbleLocation.js
Labels: 🐞버그 수정, ♻️리팩토링

#214 ✨ feat: 프로필 페이지 게시글 무한 스크롤링 적용
  src/api/postApi.js
  src/constants/pagenation.js
  src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
Labels: ✨기능 추가

#226 🎨style: 상품 상세 모달 반응형 적용
  src/components/Profile/ProductDetailCard/ProductDetailCardStyle.jsx
  src/components/common/BottomSheet/BasicModal.jsx
Labels: 🎨HTML/CSS

#222 ♻️ refactor: 이미지 업로드 시 최적화 및 예외처리
  package-lock.json
  package.json
  src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
  src/components/PostUpload/PostProductTag/PostProductTag.jsx
  src/components/PostUpload/PostTextWrite/PostTextWrite.jsx
  src/components/Product/ProductForm/ProductForm.jsx
  src/components/common/ProfileImageUpload/ProfileImageUpload.jsx
  src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
Labels: ✨기능 추가, ♻️리팩토링

#223 ♻️ refactor: 게시글 수정 페이지 컴포넌트 간소화 및 사용성 높이기
  src/atoms/post.js
  src/components/PostEdit/PostImgEdit/PostImgEdit.jsx
  src/components/PostEdit/PostImgEdit/PostImgEditStyle.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
Labels: ✨기능 추가, ♻️리팩토링

#229 ✨ feat: 목록페이지의 상단으로 이동하는 버튼 추가
  src/assets/images/top-btn.png
  src/components/common/Button/TopButton/TopButton.jsx
  src/layout/BasicLayout.jsx
Labels: ✨기능 추가

#233 🐛 fix: 캐러셀 로딩 후 첫 실행 때 가장 최근의 게시물이 잠깐 뜨는 오류 해결 및 최적화
  src/pages/HomePage/HomePage.jsx
Labels: 🐞버그 수정, ♻️리팩토링

#239 ♻️ refactor: 프로그램 실행시 로그인이 되어있는 상태에서 alert창이 뜨는 현상 해결
  src/pages/AuthenticatedPage/PrivateRoutePage.jsx
  src/pages/AuthenticatedPage/PublicRoutePage.jsx
Labels: ♻️리팩토링

#242 🐛 fix: 팔로우, 언팔로우시 깜빡임 현상 해결
  src/components/Follow/FollowButton/FollowButton.jsx
  src/components/common/Spinner/Spinner.jsx
  src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx
  src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPage.jsx
  src/pages/ProfilePage/FollowPage/FollowingsPage/FollowingsPage.jsx
Labels: 🐞버그 수정

#244 ♻️ refactor: 스와이프 기능을 Custom hook으로 빼고 ProductList에 Swipe 기능 추가
  src/components/Profile/ProductList/ProductList.jsx
  src/components/common/Tabs/SpaceTabs.jsx
  src/hooks/useSwipe.js
  src/pages/HomePage/HomePage.jsx
Labels: ✨기능 추가, ♻️리팩토링
